const express=require('express');
let {otpsignup}=require("./otpsignup.js");
let {studentlogin}=require("./studentlogin.js");
let {studentsignup}=require("./studentsignup.js");
let {forgetmail}=require("./formetmail.js");
let {otppasschange}=require("./otppasschange.js");
let {updatepass}=require("./updatepass.js");
let {ownerlogin}=require("./ownerlogin.js");
let {ownersignup}=require("./ownersignup.js");
let {otpmesssignup}=require('./otpmesssignup.js');
let {forgetmailmess}=require("./formetmailmess.js");
let {otppasschangemess}=require("./otppasschangemess.js");
let {updatepassmess}=require("./updatepassmess.js");
let {appi}=require("../student/form.js");
let {ownerapp}=require("../Owner/ownerprofile.js");
let route=express.Router();
route.use(studentlogin);
route.use(ownerapp);
route.use(appi);
route.use(updatepassmess);
route.use(otppasschangemess);
route.use(forgetmailmess);
route.use(studentsignup);
route.use(otpsignup);
route.use(forgetmail);
route.use(otppasschange);
route.use(updatepass);
route.use(ownerlogin);
route.use(ownersignup);
route.use(otpmesssignup);
module.exports={route};